version: "3"
services:
  stormserver:
    build:
      context: ./
      dockerfile: dev.dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - generated_contents:/opt/results
      - pdfs:/opt/pdf
volumes:
  generated_contents:
  pdfs: