version: "3"
services:
  stormserver:
    build:
      context: ./
      dockerfile: dev.dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - storm_generated_results:/opt/results
      - storm_pdfs/pdfs:/opt/pdf
volumes:
  storm_generated_results 
  storm_pdfs