version: "3"
services:
  stormserver:
    build:
      context: ./
      dockerfile: dev.dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./storm:/opt/results
      - ./storm/pdfs:/opt/pdf
