apiVersion: v1
kind: Secret
metadata:
  name: environments
type: Opaque
stringData:
  OpenAPIKey: {{ .Values.secrets.openAPIKey }}
  YouComKey: {{ .Values.secrets.youComKey }}
  MaxThreadNumber: "{{ .Values.secrets.maxThreadNumber }}"
  MaxConversationTurn: "{{ .Values.secrets.maxConversationTurn }}"
  MaxPerspective: "{{ .Values.secrets.maxPerspective }}"
  SearchTopK: "{{ .Values.secrets.searchTopK }}"
  OutputDir: {{ .Values.secrets.outputDir }}
  PDFStorageDir: {{ .Values.secrets.pdfStorageDir }}
  SupabaseUrl: {{ .Values.secrets.supabaseUrl }}
  SupabaseKey: {{ .Values.secrets.supabaseKey }}
  SupabaseBucket: {{ .Values.secrets.supabaseBucket }}
  Origins: {{ .Values.secrets.supabaseBucket }}
