---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-phantom-tech.ai
  namespace: traefik
spec:
  secretName: local-traefik-phantomtech-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "traefik.phantomtech.ai"
  dnsNames:
  - "traefik.phantomtech.ai"