name: storm
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - colorama=0.4.6
  - conda=24.5.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=42.0.5
  - distro=1.9.0
  - expat=2.6.2
  - fmt=9.1.0
  - frozendict=2.4.2
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libsolv=0.7.24
  - libssh2=1.11.0
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - menuinst=2.1.1
  - openssl=3.0.14
  - packaging=23.2
  - pcre2=10.42
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.4
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.4
  - truststore=0.8.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - annotated-types==0.7.0
      - anyio==4.4.0
      - arabic-reshaper==3.0.0
      - asn1crypto==1.5.1
      - attrs==23.2.0
      - babel==2.15.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorlog==6.8.2
      - courlan==1.2.0
      - cssselect2==0.7.0
      - datasets==2.14.7
      - dateparser==1.2.0
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - dill==0.3.7
      - dnspython==2.6.1
      - dspy-ai==2.4.9
      - email-validator==2.2.0
      - fastapi==0.111.1
      - fastapi-cli==0.0.4
      - filelock==3.15.4
      - flask==3.0.3
      - fonttools==4.53.1
      - fpdf2==2.7.9
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gotrue==2.6.0
      - greenlet==3.0.3
      - grpcio==1.64.1
      - grpcio-tools==1.64.1
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - html5lib==1.1
      - htmldate==1.8.1
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.5
      - hyperframe==6.0.1
      - intel-openmp==2021.4.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.3.2
      - justext==3.0.1
      - knowledge-storm==0.2.3
      - langchain-core==0.2.20
      - langchain-huggingface==0.0.3
      - langchain-qdrant==0.1.2
      - langchain-text-splitters==0.2.2
      - langsmith==0.1.89
      - lxml==5.2.2
      - lxml-html-clean==0.1.1
      - mako==1.3.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markdownify==0.13.1
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mkl==2021.4.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.15
      - networkx==3.3
      - numpy==1.26.4
      - openai==1.35.14
      - optuna==3.6.1
      - orjson==3.10.6
      - oscrypto==1.3.0
      - pandas==2.2.2
      - pillow==10.4.0
      - portalocker==2.10.1
      - postgrest==0.16.9
      - protobuf==5.27.2
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - pyhanko==0.25.1
      - pyhanko-certvalidator==0.26.3
      - pymupdf==1.24.7
      - pymupdf4llm==0.0.9
      - pymupdfb==1.24.6
      - pypdf==4.3.0
      - pypng==0.20220715.0
      - python-bidi==0.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - qdrant-client==1.10.1
      - qrcode==7.4.2
      - realtime==1.0.6
      - regex==2024.5.15
      - reportlab==4.2.2
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sentence-transformers==3.0.1
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - starlette==0.37.2
      - storage3==0.7.7
      - strenum==0.4.15
      - structlog==24.4.0
      - supabase==2.5.3
      - supafunc==0.4.7
      - svglib==1.5.1
      - sympy==1.13.0
      - tbb==2021.13.0
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tld==0.13
      - tokenizers==0.19.1
      - toml==0.10.2
      - torch==2.3.1
      - trafilatura==1.11.0
      - transformers==4.42.4
      - typer==0.12.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - tzlocal==5.2
      - ujson==5.10.0
      - uritools==4.0.3
      - uvicorn==0.30.1
      - watchfiles==0.22.0
      - webencodings==0.5.1
      - websockets==12.0
      - werkzeug==3.0.3
      - wikipedia==1.4.0
      - xhtml2pdf==0.2.16
      - xxhash==3.4.1
      - yarl==1.9.4
